### ISSUE TITLE
NullPointerException when running Example

### ISSUE THREAD

**Issue by swazza** [craigburke/document-builder#16]
First off, thanks for building this amazing library. 

I'm listing 'com.craigburke.document:pdf:0.4.2' as a maven dependency in intellij idea IDE. I then run the example groovy code you have provided on this repo's landing page. I get the following exception when I run the code. The error occurs when trying to insert the image. Removing the line of code which inserts the image does not result in any error. Any ideas as to what might be happening here or how to fix this?

```
Caught: java.lang.NullPointerException
java.lang.NullPointerException
    at org.apache.pdfbox.pdmodel.common.PDStream.<init>(PDStream.java:131)
    at org.apache.pdfbox.pdmodel.graphics.xobject.PDJpeg.<init>(PDJpeg.java:104)
    at com.craigburke.document.builder.render.ParagraphRenderer.renderImageElement(ParagraphRenderer.groovy:172)
    at com.craigburke.document.builder.render.ParagraphRenderer.this$2$renderImageElement(ParagraphRenderer.groovy)
    at com.craigburke.document.builder.render.ParagraphRenderer$_renderLine_closure3.doCall(ParagraphRenderer.groovy:139)
    at com.craigburke.document.builder.render.ParagraphRenderer.renderLine(ParagraphRenderer.groovy:132)
    at com.craigburke.document.builder.render.ParagraphRenderer.this$2$renderLine(ParagraphRenderer.groovy)
    at com.craigburke.document.builder.render.ParagraphRenderer$_renderElement_closure1.doCall(ParagraphRenderer.groovy:102)
    at com.craigburke.document.builder.render.ParagraphRenderer.renderElement(ParagraphRenderer.groovy:100)
    at com.craigburke.document.builder.render.Renderable$Trait$Helper.render(Renderable.groovy:24)
    at com.craigburke.document.builder.render.Renderable$Trait$Helper$render$0.call(Unknown Source)
    at com.craigburke.document.builder.render.ParagraphRenderer.render(ParagraphRenderer.groovy)
    at com.craigburke.document.builder.PdfDocumentBuilder$_closure3.doCall(PdfDocumentBuilder.groovy:57)
    at com.craigburke.document.core.factory.ParagraphFactory.onNodeCompleted(ParagraphFactory.groovy:40)
    at com.craigburke.document.core.builder.DocumentBuilder.super$4$invokeMethod(DocumentBuilder.groovy)
    at com.craigburke.document.core.builder.DocumentBuilder$_invokeMethod_closure1.doCall(DocumentBuilder.groovy:56)
    at com.craigburke.document.core.builder.DocumentBuilder$_invokeMethod_closure1.doCall(DocumentBuilder.groovy)
    at com.craigburke.document.core.builder.DocumentBuilder.invokeMethod(DocumentBuilder.groovy:55)
    at Example$_run_closure1$_closure2$_closure3.doCall(Example.groovy:43)
    at Example$_run_closure1$_closure2$_closure3.doCall(Example.groovy)
    at com.craigburke.document.core.builder.DocumentBuilder.super$4$invokeMethod(DocumentBuilder.groovy)
    at com.craigburke.document.core.builder.DocumentBuilder$_invokeMethod_closure1.doCall(DocumentBuilder.groovy:56)
    at com.craigburke.document.core.builder.DocumentBuilder$_invokeMethod_closure1.doCall(DocumentBuilder.groovy)
    at com.craigburke.document.core.builder.DocumentBuilder.invokeMethod(DocumentBuilder.groovy:55)
    at Example$_run_closure1$_closure2.doCall(Example.groovy:19)
    at Example$_run_closure1$_closure2.doCall(Example.groovy)
    at com.craigburke.document.core.builder.DocumentBuilder.super$4$invokeMethod(DocumentBuilder.groovy)
    at com.craigburke.document.core.builder.DocumentBuilder$_invokeMethod_closure1.doCall(DocumentBuilder.groovy:56)
    at com.craigburke.document.core.builder.DocumentBuilder$_invokeMethod_closure1.doCall(DocumentBuilder.groovy)
    at com.craigburke.document.core.builder.DocumentBuilder.invokeMethod(DocumentBuilder.groovy:55)
    at Example$_run_closure1.doCall(Example.groovy:18)
    at Example.run(Example.groovy:17)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

 If it helps, I've uploaded my idea project [here](https://github.com/swazza85/groovy-doc-builder-demo). Also, please let me know if there is any other information that I can include that can help with this issue.

Thanks for your time,
Swarup.

**Comment by swazza** [comment]
hmmm, specifying dependencies using @Grab as mentioned in the Example Groovy code, everything is working fine. Closing this issue. 

Cheers,
Swarup.

**Comment by craigburke** [comment]
Alright, cool. I'm glad you sorted it out.
